# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install libmamba
      run: |
        $CONDA/bin/conda update --name base conda
        $CONDA/bin/conda install -n base conda-libmamba-solver
        $CONDA/bin/conda config --set solver libmamba
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
        $CONDA/bin/pip install --upgrade pip
        $CONDA/bin/pip install flake8 pytest
    - name: Install package
      run: |
        $CONDA/bin/pip install ./elephant-core
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest
