# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test with pytest in 
      run: |
        make build
        make test
