# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: true
        python-version: 3.7
    - name: Install dependencies
      run: |
        conda install -c conda-forge --name base conda=4.11.0=py37h89c1867_0 mamba=0.19.1=py37h6dacc13_0
        conda env update --file environment.yml --name base
        pip install --upgrade pip
        pip install flake8 pytest
    - name: Install package
      run: |
        pip install ./elephant-core
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
